import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';

export default function Home() {
  useEffect(() => {
    fetch('/api/hello?q=peach%20and%20bowser')
      .then((response) => response.json())
      .then((data) => console.log(data));
  }, []);

  const [searchQuery, setSearchQuery] = useState('');

  const handleChange = (event) => {
    setSearchQuery(event.target.value);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Lyrics Analyzer App</title>
        <meta
          name='Analyze a song to identify whether it is clean or explicit'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <input
        onChange={handleChange}
        placeholder='Enter song/track title'
        type='search'
        value={searchQuery}
      />
      <button onClick={() => console.log('sending ' + searchQuery)}>Go</button>
    </div>
  );
}
