import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';

export default function Home() {
  const [searchQuery, setSearchQuery] = useState('');

  const handleChange = (event) => {
    setSearchQuery(event.target.value);
  };

  const handleGo = () => {
    if (!searchQuery) {
      return;
    }

    fetch(`/api/hello?q=${searchQuery}`)
      .then((response) => response.json())
      .then((data) => console.log(data));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Lyrics Analyzer App</title>
        <meta
          name='Analyze a song to identify whether it is clean or explicit'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <input
        onChange={handleChange}
        placeholder='Enter song/track title'
        type='search'
        value={searchQuery}
      />
      <button onClick={handleGo}>Go</button>
    </div>
  );
}
